application: ee4pocket
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /execute
  script: ee4pocket.application
  login: admin
- url: /.*
  script: ee4pocket.application
  secure: always
